# This workflow will build and test .NET projects

name: .NET

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-api-client:
    name: Build API Client
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/adguard-api-dotnet

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x
      - name: Restore dependencies
        run: dotnet restore AdGuard.ApiClient.slnx
      - name: Build
        run: dotnet build AdGuard.ApiClient.slnx --no-restore
      - name: Test
        run: dotnet test AdGuard.ApiClient.slnx --no-build --verbosity normal

  build-rules-compiler:
    name: Build Rules Compiler
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/rules-compiler-dotnet

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x
      - name: Restore dependencies
        run: dotnet restore RulesCompiler.slnx
      - name: Build
        run: dotnet build RulesCompiler.slnx --no-restore
      - name: Test
        run: dotnet test RulesCompiler.slnx --no-build --verbosity normal
